# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop
- master

jobs:
- job: Compile_Repo
  timeoutInMinutes: 15
  workspace:
    clean: all
  pool:
    name: 'Default'

  steps:
  - task: PowerShell@2
    inputs:
      filePath: '.\compileAll.ps1'
    displayName: 'Compiling Modules'
